# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMenu
from functools import partial
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 751)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 771, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 769, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 771, 471))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.customContextMenuRequested.connect(MainWindow.openMenu)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.barcodeText = QtWidgets.QLineEdit(self.centralwidget)
        self.barcodeText.setGeometry(QtCore.QRect(790, 70, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.barcodeText.setFont(font)
        self.barcodeText.setObjectName("barcodeText")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(790, 180, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.searchBtn.setFont(font)
        self.searchBtn.setObjectName("searchBtn")
        self.amountBox = QtWidgets.QSpinBox(self.centralwidget)
        self.amountBox.setGeometry(QtCore.QRect(900, 120, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(23)
        self.amountBox.setFont(font)
        self.amountBox.setProperty("value", 1)
        self.amountBox.setObjectName("amountBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(800, 120, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(290, 510, 491, 171))
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setDigitCount(6)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 4098.12)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 510, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(790, 20, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.amountPlus = QtWidgets.QPushButton(self.centralwidget)
        self.amountPlus.setGeometry(QtCore.QRect(960, 120, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.amountPlus.setFont(font)
        self.amountPlus.setObjectName("amountPlus")
        self.amountMinus = QtWidgets.QPushButton(self.centralwidget)
        self.amountMinus.setGeometry(QtCore.QRect(1030, 120, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.amountMinus.setFont(font)
        self.amountMinus.setObjectName("amountMinus")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(800, 330, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.productName = QtWidgets.QLineEdit(self.centralwidget)
        self.productName.setGeometry(QtCore.QRect(800, 370, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.productName.setFont(font)
        self.productName.setObjectName("productName")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(790, 420, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.price_text = QtWidgets.QLineEdit(self.centralwidget)
        self.price_text.setGeometry(QtCore.QRect(850, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.price_text.setFont(font)
        self.price_text.setObjectName("price_text")
        self.price_plus = QtWidgets.QPushButton(self.centralwidget)
        self.price_plus.setGeometry(QtCore.QRect(930, 410, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.price_plus.setFont(font)
        self.price_plus.setObjectName("price_plus")
        self.price_minus = QtWidgets.QPushButton(self.centralwidget)
        self.price_minus.setGeometry(QtCore.QRect(980, 410, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.price_minus.setFont(font)
        self.price_minus.setObjectName("price_minus")
        self.search_btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn2.setGeometry(QtCore.QRect(1050, 370, 91, 201))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.search_btn2.setFont(font)
        self.search_btn2.setObjectName("search_btn2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(790, 460, 252, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.value_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.value_1.setFont(font)
        self.value_1.setObjectName("value_1")
        self.gridLayout.addWidget(self.value_1, 0, 0, 1, 1)
        self.value_50 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.value_50.setFont(font)
        self.value_50.setObjectName("value_50")
        self.gridLayout.addWidget(self.value_50, 1, 1, 1, 1)
        self.value_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.value_20.setFont(font)
        self.value_20.setObjectName("value_20")
        self.gridLayout.addWidget(self.value_20, 1, 0, 1, 1)
        self.value_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.value_5.setFont(font)
        self.value_5.setObjectName("value_5")
        self.gridLayout.addWidget(self.value_5, 0, 1, 1, 1)
        self.value_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.value_10.setFont(font)
        self.value_10.setObjectName("value_10")
        self.gridLayout.addWidget(self.value_10, 0, 2, 1, 1)
        self.value_100 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.value_100.setFont(font)
        self.value_100.setObjectName("value_100")
        self.gridLayout.addWidget(self.value_100, 1, 2, 1, 1)
        self.pop_product = QtWidgets.QPushButton(self.centralwidget)
        self.pop_product.setGeometry(QtCore.QRect(790, 230, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.pop_product.setFont(font)
        self.pop_product.setObjectName("pop_product")
        self.getTotalBtn = QtWidgets.QPushButton(self.centralwidget)
        self.getTotalBtn.setGeometry(QtCore.QRect(790, 580, 341, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.getTotalBtn.setFont(font)
        self.getTotalBtn.setObjectName("getTotalBtn")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(800, 300, 331, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1144, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.value_1.clicked.connect(partial(MainWindow.priceBtn,1))
        self.value_5.clicked.connect(partial(MainWindow.priceBtn,5))
        self.value_10.clicked.connect(partial(MainWindow.priceBtn,10))
        self.value_20.clicked.connect(partial(MainWindow.priceBtn,20))
        self.value_50.clicked.connect(partial(MainWindow.priceBtn,50))
        self.value_100.clicked.connect(partial(MainWindow.priceBtn,100))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchBtn.setText(_translate("MainWindow", "เพิ่ม(Enter)"))
        self.label.setText(_translate("MainWindow", "จำนวน"))
        self.label_2.setText(_translate("MainWindow", "ราคารวม"))
        self.label_3.setText(_translate("MainWindow", "เพิ่มสินค้า ( บาร์โค๊ด )"))
        self.amountPlus.setText(_translate("MainWindow", "+"))
        self.amountMinus.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "เพิ่มสินค้า (อื่นๆ)"))
        self.label_6.setText(_translate("MainWindow", "ราคา"))
        self.price_text.setText(_translate("MainWindow", "0"))
        self.price_plus.setText(_translate("MainWindow", "+"))
        self.price_minus.setText(_translate("MainWindow", "-"))
        self.search_btn2.setText(_translate("MainWindow", "เพิ่ม"))
        self.value_1.setText(_translate("MainWindow", "1"))
        self.value_50.setText(_translate("MainWindow", "50"))
        self.value_20.setText(_translate("MainWindow", "20"))
        self.value_5.setText(_translate("MainWindow", "5"))
        self.value_10.setText(_translate("MainWindow", "10"))
        self.value_100.setText(_translate("MainWindow", "100"))
        self.pop_product.setText(_translate("MainWindow", "ลบรายการทั้งหมด(F1)"))
        self.getTotalBtn.setText(_translate("MainWindow", "คิดเงิน(F12)"))

