# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMenu
from functools import partial

class Ui_MainWindow(object):
    def openMenu(self,event):
        menu = QMenu()
        quitAction = menu.addAction("Quit")
        action = menu.exec_(self.tableWidget.mapToGlobal(event))
        if action == quitAction:
            qApp.quit()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 641, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 639, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 641, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.customContextMenuRequested.connect(MainWindow.openMenu)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.barcodeText = QtWidgets.QLineEdit(self.centralwidget)
        self.barcodeText.setGeometry(QtCore.QRect(660, 60, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.barcodeText.setFont(font)
        self.barcodeText.setObjectName("barcodeText")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(660, 180, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.searchBtn.setFont(font)
        self.searchBtn.setObjectName("searchBtn")
        self.amountBox = QtWidgets.QSpinBox(self.centralwidget)
        self.amountBox.setGeometry(QtCore.QRect(770, 120, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.amountBox.setFont(font)
        self.amountBox.setProperty("value", 1)
        self.amountBox.setObjectName("amountBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(700, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(160, 520, 491, 171))
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setDigitCount(6)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 4098.12)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 510, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(55)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(660, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.amountPlus = QtWidgets.QPushButton(self.centralwidget)
        self.amountPlus.setGeometry(QtCore.QRect(850, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.amountPlus.setFont(font)
        self.amountPlus.setObjectName("amountPlus")
        self.amountMinus = QtWidgets.QPushButton(self.centralwidget)
        self.amountMinus.setGeometry(QtCore.QRect(920, 120, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.amountMinus.setFont(font)
        self.amountMinus.setObjectName("amountMinus")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(660, 300, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.productName = QtWidgets.QLineEdit(self.centralwidget)
        self.productName.setGeometry(QtCore.QRect(740, 350, 241, 31))
        self.productName.setObjectName("productName")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(660, 350, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(670, 400, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.price_text = QtWidgets.QLineEdit(self.centralwidget)
        self.price_text.setGeometry(QtCore.QRect(740, 400, 81, 31))
        self.price_text.setObjectName("price_text")
        self.price_plus = QtWidgets.QPushButton(self.centralwidget)
        self.price_plus.setGeometry(QtCore.QRect(820, 390, 61, 51))
        self.price_plus.setObjectName("price_plus")
        self.price_minus = QtWidgets.QPushButton(self.centralwidget)
        self.price_minus.setGeometry(QtCore.QRect(880, 390, 61, 51))
        self.price_minus.setObjectName("price_minus")
        self.search_btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn2.setGeometry(QtCore.QRect(920, 440, 91, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.search_btn2.setFont(font)
        self.search_btn2.setObjectName("search_btn2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(670, 440, 252, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.value_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.value_1.setObjectName("value_1")
        self.gridLayout.addWidget(self.value_1, 0, 0, 1, 1)
        self.value_50 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.value_50.setObjectName("value_50")
        self.gridLayout.addWidget(self.value_50, 1, 1, 1, 1)
        self.value_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.value_20.setObjectName("value_20")
        self.gridLayout.addWidget(self.value_20, 1, 0, 1, 1)
        self.value_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.value_5.setObjectName("value_5")
        self.gridLayout.addWidget(self.value_5, 0, 1, 1, 1)
        self.value_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.value_10.setObjectName("value_10")
        self.gridLayout.addWidget(self.value_10, 0, 2, 1, 1)
        self.value_100 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.value_100.setObjectName("value_100")
        self.gridLayout.addWidget(self.value_100, 1, 2, 1, 1)
        self.pop_product = QtWidgets.QPushButton(self.centralwidget)
        self.pop_product.setGeometry(QtCore.QRect(660, 230, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pop_product.setFont(font)
        self.pop_product.setObjectName("pop_product")
        self.getTotalBtn = QtWidgets.QPushButton(self.centralwidget)
        self.getTotalBtn.setGeometry(QtCore.QRect(670, 580, 341, 111))
        font = QtGui.QFont()
        font.setPointSize(65)
        self.getTotalBtn.setFont(font)
        self.getTotalBtn.setObjectName("getTotalBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.value_1.clicked.connect(partial(MainWindow.priceBtn,1))
        self.value_5.clicked.connect(partial(MainWindow.priceBtn,5))
        self.value_10.clicked.connect(partial(MainWindow.priceBtn,10))
        self.value_20.clicked.connect(partial(MainWindow.priceBtn,20))
        self.value_50.clicked.connect(partial(MainWindow.priceBtn,50))
        self.value_100.clicked.connect(partial(MainWindow.priceBtn,100))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchBtn.setText(_translate("MainWindow", "เพิ่ม (Enter)"))
        self.label.setText(_translate("MainWindow", "จำนวน"))
        self.label_2.setText(_translate("MainWindow", "ราคา"))
        self.label_3.setText(_translate("MainWindow", "เพิ่มสินค้า ( บาร์โค๊ด )"))
        self.amountPlus.setText(_translate("MainWindow", "+\n(F9)"))
        self.amountMinus.setText(_translate("MainWindow", "-\n(F10)"))
        self.label_4.setText(_translate("MainWindow", "เพิ่มสินค้า (อื่นๆ)"))
        self.label_5.setText(_translate("MainWindow", "ชื่อสินค้า"))
        self.label_6.setText(_translate("MainWindow", "ราคา"))
        self.price_text.setText(_translate("MainWindow", "0"))
        self.price_plus.setText(_translate("MainWindow", "+"))
        self.price_minus.setText(_translate("MainWindow", "-"))
        self.search_btn2.setText(_translate("MainWindow", "เพิ่ม"))
        self.value_1.setText(_translate("MainWindow", "1"))
        self.value_50.setText(_translate("MainWindow", "50"))
        self.value_20.setText(_translate("MainWindow", "20"))
        self.value_5.setText(_translate("MainWindow", "5"))
        self.value_10.setText(_translate("MainWindow", "10"))
        self.value_100.setText(_translate("MainWindow", "100"))
        self.pop_product.setText(_translate("MainWindow", "สินค้าขายดี"))
        self.getTotalBtn.setText(_translate("MainWindow", "คิดเงิน"))

